#!/usr/bin/python3

import qrcode
import os

def main():
    print("Gerador de QRCode via CLI!")
    link = input("Link para gerar o qr: ")
    qr = qrcode.QRCode(
            version=1,
            box_size=4,
            border=5)

    qr.add_data(link)
    qr.make(fit=True)
    img = qr.code_image(fill='black', back_color='white')
    img.show()

    print("Gerar outro qrcode?\nS - sim\nN - Nao\n")
    aux = input("--> ")
    if aux == "S" or aux == "s":
        os.system("clear && sleep 1")
        main()
    else:
        print("Saindo...")
        os.system("sleep 1 && clear")

main()
